import type { Metadata } from "next";
import "./globals.css";
import Nav from "../components/Nav";
import Providers from "../redux/Providers"; // ✅ Đổi tên cho đúng
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased text-gray-900">
        <Providers>
          <div className="min-h-screen grid grid-rows-[auto_1fr_auto]">
            <Nav />

            {/* Body content chiếm hết không gian còn lại */}
            <main className="py-4 px-3 bg-[#F7FAFC]">
              {children}
            </main>

            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
